name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.11
        environment-file: environment.yml
        auto-activate-base: false

    - name: Activate Conda environment
      run: conda activate brewery-finder && pytest
